= Applications declaration
:description: Applications declaration

In Bonita Central, we refer as application to the entity that will be built and run by Bonita. It is the content of a unique Git repository.
One Runtime will be able to host several applications that share the same Business Data Model.

== Prerequisites
. All Runtimes (nodes) linked to an application space should have the same version.
. To facilitate the data exchange, install Bonita Central in the same network as your Bonita Runtimes. If not, since Bonita Central requires direct access to the nodes, authorization to the network will be required. See xref:ROOT:network-configuration.adoc[network configuration] for details.
. Have Bonita Runtime admin credentials

== How to declare an application ?

After installing Bonita Central, the first thing you will have to do is adding the applications you want to supervise.
Nothing easier because you will be able to do it directly from the overview page.

The only information you will have to provide is :

* A name and a description for the application. Make it transparent both for technical and business users
* Runtime end point to access it : URL, IP address. For Runtimes in a cluster it will be load balancer's URL/IP address.
* Connection credentials - Bonita Runtime admin username and password. Unless you use LDAP authentication, the information provided will not be stored in Bonita Central, being used only to establish a connection with the engine.

[NOTE]
====
If one of the following authentication method is used : Basic authentication, LDAP, SSO, the following should be applied:

* The username should be known in Bonita Runtime organization
* The username should not be assigned to a real member of your organization
* Assign admin authorization rights to the username
* The credentials will only be used for data exchange
====

[WARNING]
====
If you are using the LDAP authentication method, an LDAP user is still required for monitoring. We recommend that you follow this procedure:

* Choose a username in your LDAP directory (a technical account as described in above note)
* Assign admin authorization rights to the username
* With this username, declare the list of applications you want to monitor
* Remove the admin authorization rights from the username afterward
* The username will still be used to monitor the applications, without the need for admin authorization rights
====

=== Establishing a connection with Bonita Runtime

Once Bonita Central will connect to Bonita Runtime, an agent will be installed in Bonita Runtime. Also, a dedicated technical user only authorized to exchange data with Bonita Central will be then created in Bonita Runtime organization with the appropriate permissions.  This user will be only authorized to exchange data with Bonita Central.

[WARNING]
====
In order for those permissions to be taken into account, a restart of Bonita Runtime is required.
====

Once application's card is in green status, healthcheck, monitoring and configuration for the application are available.

