= Configuration in Bonita Central
:description: Configuration in Bonita Central

As soon as an application is connected to Bonita Central, you can access to Runtime's configuration from the application card. +
It is displayed as a single (paginated) table, with three columns: the configuration attribute, the value of the attribute and the related configuration file path.

[NOTE]
The configuration is in read-only mode meaning that it is not possible to change it from Bonita Central. Using setup tool will be required for the moment. 

== Searching

Since there are many configuration attributes in a Bonita Runtime, the search feature is essential.
You can search any string, from the configuration attribute names, attribute values, or configuration files.

For instance, enter "hibernate-cache" to display the configuration related to Hibernate caching.

== Sorting

Per column, sort the page alphabetically by clicking on the column header.

== Downloading the configuration

You can download the whole configuration as a JSON format by clicking on the download button.
It may be used for offline analysis or sent to the Bonita support team.
