= Bonita Central
:description: Bonita Central.

[CAUTION]
====
* internal link xref:::i-do-not-exist.adoc[do not exist internal]
* bonita link xref:{bonitaVersion}@bonita::performance-tuning_NOT_EXIST.adoc[do not exist bonita]
====


Welcome to Bonita Central, the production management tool that: 

- “has all in one place” for configuration 

- “knows all” for monitoring and error analysis (logs)

Learn how to use the Bonita Central and all of its components.

[NOTE]
====
Bonita Central is only available under license. 
====

== Motivations

The need of a central supervision and administration tool has been expressed by our customers using multi-runtimes. 

Technical monitoring is a need users are having with BPMN tools for years. Bonita Central aims to make things clear not only for technical live monitoring and health status but also for Bonita Runtime's configuration. 

For Runtimes - individual or in cluster: 

- directly from the overview page it will be possible to live monitor all Bonita nodes health status in a single look 

- it will be possible to visualize the current configuration and download it under json format file

== What's in it for you? 

In this first release, healthcheck of all the declared applications in a single dashboard. Up to 12 application-cards on the overview page without scrolling. Perfect visual management for your ops team!

Based on years of support experience, we have identified common patterns and mistakes that “Bonita Central” will help you solve before it becomes an issue on your environment and you'll have to contact Bonitasoft Support. 

For each application, directly from “Bonita Central” you can deep dive into the Monitoring view to better qualify the issue. When necessary the last known application configuration is available, even when the application is stopped or down. This way, in case of issue related to a bad configuration the information will be available within your fingertips.

== Prerequisites
Runtimes in cluster have to be in the same technical version. 

== Supported Bonita Runtime version

[WARNING]
====
Bonita Runtimes configured in multi-tenancy are not supported.
====

[%header,cols="1,1"]

|===
|Bonita Central component
|Runtimes - individual or in cluster

|Health-check
|7.12.x, 7.13.x, 7.14.x, 7.15.x, 8.0.x

|Configuration
|7.12.x, 7.13.x, 7.14.x, 7.15.x, 8.0.x

|Monitoring
|7.13.x, 7.14.x, 7.15.x, 8.0.x

|===

*Bonita Central* will be able to connect and display information in : 

- Degraded mode with Bonita Runtime from 2021.1 till Bonita Runtime 2022.2 based on their technical capabilities 
- Full mode starting  with Bonita Runtime 2023.1

Not available with *Bonita Central*:

- Monitoring of Bonita Runtimes with expired license
- Do changes in Bonita Runtime
- Manage a process or a case
- Save monitoring data for further analysis 

